### ISSUE TITLE
Allow alphanumeric zone numbers in Elasticsearch

### ISSUE THREAD

**Issue by stevenrombauts** [belgianpolice/internet-platform#104]
Add support for the new subsites that do do not have a zone number. Todo's:

- Update the column mapping
- Work with index aliases (http://www.elasticsearch.org/blog/changing-mapping-with-zero-downtime/)

**Comment by stevenrombauts** [comment]
Tom, could you please test this on staging? Creating a ticket in the /fed subsite should work and show up in /manager support component.

**Comment by tomjanssens** [comment]
Fix confirmed on staging.
