### ISSUE TITLE
Extend social links

### ISSUE THREAD

**Issue by tomjanssens** [belgianpolice/internet-platform#109]
Currently we have a `twitter` and `facebook` column in `data.police_zones`.

Replace this with one generic `social` column that contains a JSON stream of all the social channels:

    {
    "twitter":
      {"nl": "account_nl", "fr": "account_fr"},
    "facebook":
      {"nl": "account_nl", "fr": "account_fr"}
    }

This will allow multilingual zones to have a different social channels for each language. Based on the `language` column we can migrate the existing data:

1. Dutch
2. French
3. Dutch & French
4. German

**Comment by stevenrombauts** [comment]
Deployed to staging and migration has been applied there. 

@tomjanssens  Could you test the following please:

* Make sure the social links show up correctly
* Check the zones database table and see if migration succeeded.

**Comment by tomjanssens** [comment]
Deployed.
