### ISSUE TITLE
Remove offset from links to different category

### ISSUE THREAD

**Issue by stevenrombauts** [belgianpolice/internet-platform#118]
Some components browse items based on a certain model state. The pagination offset however, is being added to all links to the same view across the entire model and fails to distinguish between the state value where necessary

Components affected:
* questions
* wanted

**Comment by stevenrombauts** [comment]
Could you test this on staging, Tom?

1. Force page 2 by setting the offset manually by browsing to http://staging.lokalepolitie.be/5388/vragen/parkeren?limit=2&offset=2 and then browse to another category. You should get the first one in the list.
2. Go to page 2 of this list in com:wanted at http://staging.lokalepolitie.be/fed/nl/opsporingen/vermist/minderjarigen?offset=10 and then on to another section/category. Pagination should be reset.

**Comment by tomjanssens** [comment]
Can you test again? No more `offset=0` in the URL.

**Comment by stevenrombauts** [comment]
Great, works perfectly! Deployed to production.
