### ISSUE TITLE
Error when referrer Cookie is empty

### ISSUE THREAD

**Issue by tomjanssens** [belgianpolice/internet-platform#96]
When the referrer Cookie is not set the following error is returned.

`Exception 'UnexpectedValueException' with message 'The url must be a array as returned by parse_$this->getView()->getUrl()->toString() a string or object implementing __toString(), "NULL" given.' in /library/http/url/url.php:254`

Lets add a fallback.

Replication:
* Open a article in the administrator
* Remove the `referrer` cookie
* Preform a `save` or `cancel` action

Reported by 5385

**Comment by johanjanssens** [comment]
If the referrer cookie is empty the fallback can be to use the referrer
itself. This is not 100% correct but will work.

On Tue, Feb 24, 2015 at 4:01 PM, Tom Janssens <notifications@github.com>
wrote:

> When the referrer Cookie is not set the following error is returned.
>
> Exception 'UnexpectedValueException' with message 'The url must be a array
> as returned by parse_$this->getView()->getUrl()->toString() a string or
> object implementing __toString(), "NULL" given.' in
> /library/http/url/url.php:254
>
> Lets add a fallback.
>
> Reported by 5385
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/belgianpolice/internet-platform/issues/96>.
>



-- 

[image: --]

Johan Janssens
[image: http://]about.me/johanjanssens
<http://about.me/johanjanssens?promo=email_sig>

**Comment by tomjanssens** [comment]
Deployed.
